### ISSUE TITLE
Release completely static binaries

### ISSUE THREAD

**Issue by cmur2** [camunda-ci/github-backup#2]
Would be nice to be able to run it on Docker containers with Alpine.

**Comment by jsam** [comment]
@cmur2 I just bumped the version with statically compiled binary. You can check the latest version with ```ldd``` it should confirm that.

Since this is not a practice on all Golang projects I would suggest you look into ```gliderlabs/alpine``` image which should support Go's dynamically compiled binaries.

I will close this ticket for now. If you still have problems with it, please let me know.
